---
- name: Install Server Jenkins
  hosts: serverjenkins
  become: true

  roles:
    - java
    - jenkins

  post_tasks:

    - name: Ensure Jenkins is running.
      uri:
        url: "http://127.0.0.1:8080/"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
